meta_product_name: "Victoire Vager"
meta_title: "Victoire Vager | Portfolio"
meta_description: "Portfolio de Victoire Vager, Chargée de Communication"
meta_image: "me.svg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
