meta_product_name: "Violaine Quinchon"
meta_title: "Violaine Quinchon | Portfolio"
meta_description: "Portfolio de Violaine Quinchon, Responsable de Communication Interne"
meta_image: "me.svg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
